---
- name: Reboot machine(s)
  hosts: all

  ## Optional: Set a reboot reason to be displayed
  #  by Ansible. Role will have a default value if
  #  none is set here.
  #
  #  Make sure to comment the vars: section if you
  #  are not setting a reboot_reason
  # vars:
  #   reboot_reason: "Planned reboot"

  roles:
    - { role: roles/maint/reboot-system }
