---
- name: "[Cron] Check if Cron is installed"
  ansible.builtin.stat:
    path: /usr/bin/crontab
  register: cron_bin

- name: "[All OS Types] [Cron] Schedule daily clear of Bash history"
  ansible.builtin.cron:
    name: "Clear bash history every night at 11pm"
    minute: "0"
    hour: "23"
    job: "cat /dev/null > ~/.bash_history"
    user: "{{ remote_host_user }}"
  when: cron_bin.stat.exists
