---
- name: Set host SSH port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port\s+'
    line: "Port {{ netbird_host_ssh_port }}"
    backup: true
  notify: restart sshd

- name: Set root login policy
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin\s+'
    line: "PermitRootLogin {{ 'yes' if netbird_enable_peer_ssh_root | bool else 'no' }}"
    backup: true
  notify: restart sshd

- name: Ensure ssh service is enabled
  service:
    name: "{{ 'sshd' if ansible_os_family in ['RedHat', 'Suse'] else 'ssh' }}"
    enabled: true
    state: started
