---
- name: "[UFW] Check if UFW package is installed"
  ansible.builtin.package_facts:
    manager: auto

- name: "[Debian Family] [UFW] Install UFW"
  ansible.builtin.apt:
    name: "ufw"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: "[Debian Family] [XRDP] Install XRDP"
  ansible.builtin.apt:
    name: "xrdp"
    state: present
  become: true
  when: ansible_facts["os_family"] == "Debian"
