---
- name: Configure systems using Ansible Roles
  hosts: all

  roles:
    - ../roles/common/installs/install-default-packages
    - ../roles/common/installs/install-neovim
    - ../roles/common/installs/install-tmux
    - ../roles/common/installs/install-duplicati
    - ../roles/common/installs/install-tailscale
    - ../roles/common/configure/remove-snaps
    - ../roles/security/install-firewall
    - ../roles/security/ssh-setup
