---
- name: Configure systems using Ansible Roles
  hosts: all

  vars:
    nodejs_ver: "18.x" # For Debian family
    nodejs_stream: "18" # For RedHat family

    # defaults file for duplicati
    duplicati_web_port: 8200
    duplicati_ver: "2.0.7.1-1"

  roles:
    - { role: roles/common/install/install-default-packages }
    - { role: roles/common/install/install-neovim }
    - { role: roles/common/install/install-tmux }
    # - {role: roles/common/install/install-duplicati }
    - { role: roles/common/install/install-tailscale }
    - { role: roles/common/configure/remove-snaps }
    - { role: roles/security/install-firewall }
    - { role: roles/security/ssh-setup }
