#SPDX-License-Identifier: MIT-0
---
# tasks file for package_installer
- name: Install specified packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item }}"
  when: packages | length > 0
