---
- name: "[All OS Types] Find all log files older than 7 days"
  find:
    paths: /
    patterns: "*.log"
    age: "7d"
    recurse: yes
  become: true
  register: logs_to_remove

- name: "[All OS Types] Delete all found logs"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ logs_to_remove.files }}"
  become: true
