---

## Check if Duplicati is installed using Ansible facts
- name: "[All OS Types] [Duplicati Setup] Check packages"
  ansible.builtin.package_facts:
    manager: auto

- include_tasks: install_duplicati_debian_family.yml
  when: (ansible_facts['os_family'] == "Debian") and ("duplicati" not in ansible_facts.packages)

- include_tasks: post_install_debian_family.yml
  when: (ansible_facts['os_family'] == "Debian")

- include_tasks: post_install_redhat_family.yml
  when: (ansible_facts['os_family'] == "RedHat")

- include_tasks: cleanup_debian_family.yml
  when: (ansible_facts['os_family'] == "Debian")
