---
- name: "Create Cron job for clear ~/.bash_history"
  hosts: all

  tasks:
    - ansible.builtin.import_role:
        name: common/configure/configure-cron
        tasks_from: schedule_clear_bash_history.yml
