---
netbird_service_name: netbird
netbird_package_name: netbird
netbird_prereq_packages:
  - ca-certificates
  - curl
  - gnupg

netbird_repo_key_url: https://pkgs.netbird.io/debian/public.key
netbird_repo_keyring: /usr/share/keyrings/netbird-archive-keyring.gpg
netbird_repo_line: "deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main"
