---
- name: Enable ufw
  community.general.ufw:
    state: "enabled"
    policy: "deny"
    logging: "on"
  become: true
  when: ansible_os_family == "Debian"

- name: ufw rules
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "22"
    - "80"
    - "443"
    # - "9090" # Cockpit
    # - "8200" # Duplicati web
  become: true
  when: ansible_os_family == "Debian"