---
# tasks file for roles/security/install-firewall

- name: "[Debian Family] [Firewall] Install UFW firewall"
  include_tasks: install_firewall_debian_family.yml
  when: ansible_facts['os_family'] == "Debian"

- name: "[Debian Family] [Firewall] Configure UFW firewall"
  include_tasks: configure_firewall_debian_family.yml
  when: ansible_facts['os_family'] == "Debian"

- name: "[RedHat Family] [Firewall] Install Firewalld"
  include_tasks: install_firewall_redhat_family.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: "[RedHat Family] [Firewall] Configure Firewalld"
  include_tasks: configure_firewall_redhat_family.yml
  when: ansible_facts['os_family'] == "RedHat"
