---
- name: Uninstall Nomad
  hosts: all

  tasks:
    - name: "Uninstall Nomad"
      ansible.builtin.import_role:
        name: uninstall/uninstall-hashi-apps
        tasks_from: uninstall-nomad.yml

    - name: "Post-Uninstall Nomad Cleanup"
      ansible.builtin.import_role:
        name: uninstall/uninstall-hashi-apps
        tasks_from: uninstall-nomad_cleanup.yml

    - name: "Reboot server. Reason: Nomad uninstall"
      ansible.builtin.import_role:
        - { role: roles/maint/reboot-system }
