---
## https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml

## Note: will use vars from ./group_vars/all.yml
all:

  hosts:
    # (example) ubuntu4:
      # ansible_host: 192.168.1.xxx
      # ansible_port: xxxx
      # ansible_ssh_user: <user2>

inventory:

  hosts:
    # (example) ubuntu4:

autoReboot:

  hosts:
    # (example) ubuntu4:
