---
## https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml

all:
  hosts:
    example-host:
      ansible_ssh_host: "192.168.1.xxx"

autoReboot:
  ## Hosts that are allowed automated reboots, i.e. for maintenance
  hosts:

debian:
  hosts:

ubuntu:
  hosts:

dockerHosts:
  hosts:

raspberryPi:
  hosts:

# ------------------------------------------------------------------- #
disabledHosts:
  ## Add hosts to this section that you want to keep a record of, but
  #  don't want to be picked up by playbooks, i.e. a server that's powered
  #  down currently but will be back online eventually.
  #
  #  Make sure the hosts are commented, or they will still be picked up by
  #  Ansible.
  hosts:
    # (example) ubuntu4:
    #   ansible_host: 192.168.1.xxx
    #   ansible_port: xxxx
    #   ansible_ssh_user: <user2>
