---
- name: "Configure NetBird logging"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Gather facts
      ansible.builtin.import_role:
        name: my.homelab.facts

    - name: Configure logging
      ansible.builtin.import_role:
        name: my.homelab.netbird
        tasks_from: logging.yml
