---
- name: "NetBird Healthcheck"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Gather facts
      ansible.builtin.import_role:
        name: my.homelab.facts

    - name: Run health check
      ansible.builtin.import_role:
        name: my.homelab.netbird
        tasks_from: health.yml
