---
##############################################################
# Restart the client and verify socket & service are working #
##############################################################

- name: "Reconcile NetBird state"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Gather facts
      ansible.builtin.import_role:
        name: my.homelab.facts

    - name: Reconcile NetBird
      ansible.builtin.import_role:
        name: my.homelab.netbird
        tasks_from: reconcile.yml
