---
- name: "Uninstall NetBird"
  hosts: all
  become: true
  gather_facts: true

  vars:
    netbird_purge_data: true

  tasks:
    - name: "Gather facts"
      ansible.builtin.import_role:
        name: my.homelab.facts

    - name: "Uninstall NetBird"
      ansible.builtin.import_role:
        name: my.homelab.netbird
        tasks_from: uninstall.yml

    - name: "Clean NetBird state before re-enroll"
      ansible.builtin.import_role:
        name: my.homelab.netbird
        tasks_from: clean.yml
      when: netbird_purge_data | bool
      failed_when: false
