---
- name: "Install Docker dependencies (Debian)"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3-debian
    state: present
    update_cache: true
  become: true
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: "Install Docker dependencies (RHEL/CentOS/Fedora)"
  ansible.builtin.package:
    name:
      - yum-utils
      - dnf-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  become: true
  when:
    - ansible_facts['os_family'] == 'RedHat'
