###########
# Ansible #
###########
ansible_python_interpreter: "/usr/bin/python3"

## User for connection. I use a service account, "ansible_svc"
ansible_ssh_user: "ansible_svc"
## Path to SSH key (note: you must copy this to the host with ssh-copy-id before using Ansible)
ansible_ssh_private_key_file: "/home/user/.ssh/ansible_id_rsa"

## For path substitution, i.e. "/home/{{ remote_host_user }}"
remote_host_user: "exampleuser"

tailscale_preauth_key: ""
