---
- name: "[Debian Family] [QEMU Guest Agent] Update apt repo and cache"
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: true
  when: ansible_distribution == "Debian"

- name: "[Debian Family] [QEMU Guest Agent] Install qemu-guest-agent"
  apt:
    name: "qemu-guest-agent"
    state: present
  become: true
  when: ansible_os_family == "Debian"
