---
- name: "[RedHat Family] [Dotfiles] Check if .config dir exists"
  stat:
    path: "/home/{{ remote_host_user }}/.config/"
  become: true
  register: home_config_dir

- name: "[RedHat Family] [Dotfiles] Check if .bash_aliases_fedora_override exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_aliases_fedora_override"
  become: true
  register: bash_aliases_fedora_override
  when: ansible_distribution == "Fedora"

- name: "[RedHat Family] [Dotfiles] Check if .bash_aliases_suse_override exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_aliases_suse_override"
  become: true
  register: bash_aliases_suse_override
  when: ansible_distribution == "SUSE"

## Tasks

- name: "[Debian] [Dotfiles] Create .bash_aliases_fedora_override"
  template:
    src: bash/.bash_aliases_fedora_override.j2
    dest: "/home/{{ remote_host_user }}/.bash_aliases_fedora_override"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true
  when: ansible_facts['distribution'] == "Fedora"

- name: "[Debian] [Dotfiles] Create .bash_aliases_suse_override"
  template:
    src: bash/.bash_aliases_suse_override.j2
    dest: "/home/{{ remote_host_user }}/.bash_aliases_suse_override"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true
  when: ansible_facts['distribution'] == "SUSE"
