---
# tasks file for duplicati

- name: "[Debian Family] [Duplicati] Install dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mono-devel
  become: true
  when: ansible_facts['os_family'] == "Debian"

# - name: Check if Duplicati is installed
#   command: dpkg-query -W duplicati
#   register: duplicati_installed
#   failed_when: duplicati_installed.rc > 1
#   changed_when: duplicati_installed.rc == 1

- name: Download Duplicati v{{ duplicati_ver }}
  get_url:
    url="https://updates.duplicati.com/beta/duplicati_{{ duplicati_ver }}_all.deb"
    dest="/home/{{ remote_host_user }}/duplicati_{{ duplicati_ver }}_all.deb"
  become: true
  when: (ansible_facts['os_family'] == "Debian") # and (duplicati_installed.rc == 1)

- name: Install Duplicati v{{ duplicati_ver }}
  apt:
    deb: "/home/{{ remote_host_user }}/duplicati_{{ duplicati_ver }}_all.deb"
  become: true
  when: (ansible_facts['os_family'] == "Debian") # and (duplicati_installed.rc == 1)
