---

- name: "[Debian Family] [Duplicati] Create systemd service for Duplicati"
  template:
    src: duplicati.service.j2
    dest: /etc/systemd/system/duplicati.service
    owner: root
    group: root
    mode: 0644
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "[Debian Family] [Duplicati] Create Duplicati config"
  template:
    src: duplicati.j2
    dest: /etc/default/duplicati
    owner: root
    group: root
    mode: 0644
  become: true

- name: "[UFW] Allow Duplicati port (8200)"
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "8200" # Duplicati web
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Start & enable Duplicati service
  service:
    name: duplicati
    enabled: true
    state: started
  become: true
