---
# tasks file for roles/security/install-firewall
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install firewall
  ansible.builtin.include_tasks: install-firewall.yml

- name: Configure optional IP sets
  ansible.builtin.include_tasks: ipset.yml
  when: firewall_ipset_enabled | bool
