---

- include_tasks: install_tailscale_debian_family.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: install_tailscale_redhat_family.yml
  when: ansible_facts['os_family'] == "RedHat"
