---
# tasks file for install-clamav
- name: "[All OS Types] [ClamAV Setup] Check packages"
  ansible.builtin.package_facts:
    manager: auto

- include_tasks: install_clamav.yml
  when: ("clamav" not in ansible_facts.packages)

- include_tasks: restart_clamav_systemd.yml
  when: ("clamav" in ansible_facts.packages)

- include_tasks: configure_scans.yml
