---
- name: "[All OS Types] [Dotfiles] Check if .bash_aliases exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_aliases"
  become: true
  register: bash_aliases

- name: "[All OS Types] [Dotfiles] Check if .bash_functions exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_functions"
  become: true
  register: bash_functions

- name: "[All OS Types] [Dotfiles] Check if .bash_loader exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_loader"
  become: true
  register: bash_loader

## Tasks

- name: "[All OS Types] [Dotfiles] Create .bash_aliases"
  template:
    src: bash/.bash_aliases.j2
    dest: "/home/{{ remote_host_user }}/.bash_aliases"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true

- name: "[All OS Types] [Dotfiles] Create .bash_functions"
  template:
    src: bash/.bash_functions.j2
    dest: "/home/{{ remote_host_user }}/.bash_functions"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true

- name: "[All OS Types] [Dotfiles] Create .bash_loader"
  template:
    src: bash/.bash_loader.j2
    dest: "/home/{{ remote_host_user }}/.bash_loader"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true
