---
- name: "[Debian Family] [Dotfiles] Check if .config dir exists"
  stat:
    path: "/home/{{ remote_host_user }}/.config/"
  become: true
  register: home_config_dir

- name: "[Debian Family] [Dotfiles] Check if .bash_aliases_ubuntu_override exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_aliases_ubuntu_override"
  become: true
  register: bash_aliases_ubuntu_override
  when: ansible_distribution == "Ubuntu"

- name: "[Debian Family] [Dotfiles] Check if .bash_aliases_debian_override exists"
  stat:
    path: "/home/{{ remote_host_user }}/.bash_aliases_debian_override"
  become: true
  register: bash_aliases_debian_override
  when: ansible_distribution == "Debian"

## Tasks

- name: "[Debian] [Dotfiles] Create .bash_aliases_debian_override"
  template:
    src: bash/.bash_aliases_debian_override.j2
    dest: "/home/{{ remote_host_user }}/.bash_aliases_debian_override"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true
  when: ansible_facts['distribution'] == "Debian"

- name: "[Debian] [Dotfiles] Create .bash_aliases_ubuntu_override"
  template:
    src: bash/.bash_aliases_ubuntu_override.j2
    dest: "/home/{{ remote_host_user }}/.bash_aliases_ubuntu_override"
    owner: "{{ remote_host_user }}"
    group: "{{ remote_host_user }}"
    mode: "0777"
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"
