---
# tasks file for roles/common/configure-dotfiles

- name: "[All OS Types] [Dotfiles] Create default dotfiles"
  include_tasks: configure_dotfiles_all.yml

- name: "[Debian Family] [Dotfiles] Create Debian family dotfiles"
  include_tasks: configure_dotfiles_debian_family.yml
  when: ansible_facts['os_family'] == "Debian"

- name: "[RedHat Family] [Dotfiles] Create RedHat family dotfiles"
  include_tasks: configure_dotfiles_redhat_family.yml
  when: ansible_facts['os_family'] == "RedHat"
