#SPDX-License-Identifier: MIT-0
---
- name: Install Coolify
  include_tasks: install.yml
  when: coolify_action == "install"

- name: Uninstall Coolify
  include_tasks: uninstall.yml
  when: coolify_action == "uninstall"

- name: Management tasks
  include_tasks: management.yml
  when: coolify_action in ("update", "restart", "stop")
