---
- name: Override Docker networking
  lineinfile:
    path: /data/coolify/.env
    regexp: "^DOCKER_ADDRESS_POOL_BASE="
    line: "DOCKER_ADDRESS_POOL_BASE={{ coolify_docker_pool_base }}"
  notify: restart coolify
  become: true

- name: Disable autoupdate
  lineinfile:
    path: /data/coolify/.env
    regexp: "^AUTOUPDATE="
    line: "AUTOUPDATE={{ coolify_autoupdate | lower }}"
  notify: restart coolify
  become: true

- name: Change port (if given a port other than 8000)
  replace:
    path: /data/coolify/docker-compose.yml
    regexp: '":8000"'
    replace: '":{{ coolify_port }}"'
  when: coolify_port != 8000
  notify: restart coolify
  become: true
