---
- name: Ensure Coolify .env directory exists
  file:
    path: /data/coolify
    state: directory
    mode: "0755"
  become: true

- name: Override Docker networking
  lineinfile:
    path: /data/coolify/source/.env
    regexp: "^DOCKER_ADDRESS_POOL_BASE="
    line: "DOCKER_ADDRESS_POOL_BASE={{ coolify_docker_pool_base }}"
    create: true
    mode: "0644"
  become: true
  notify: restart coolify

- name: Disable autoupdate
  lineinfile:
    path: /data/coolify/source/.env
    regexp: "^AUTOUPDATE="
    line: "AUTOUPDATE={{ coolify_autoupdate | lower }}"
    create: true
    mode: "0644"
  become: true
  notify: restart coolify
