---
- name: Install dependencies
  yum:
    name: ["curl", "git"]
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install Neovim
  yum:
    name: ["neovim", "python3-neovim"]
    state: present
  become: true
  when: ansible_os_family == "RedHat"
