---
# tasks file for roles/common/configure-neovim

## Get all installed packages
- name: "[All OS Types] [Neovim] Check packages"
  ansible.builtin.package_facts:
    manager: auto

## FILE/DIRECTORY CHECKS
- name: Check if .config dir exists
  stat:
    path: "/home/{{ remote_host_user }}/.config/"
  become: true
  register: home_config_dir

- name: Check if nvim directory exists
  stat:
    path: "/home/{{ remote_host_user }}/.config/nvim/"
  become: true
  register: nvim_conf_dir

## Tasks
- name: "[Debian Family] [Neovim] Run NodeJS {{ nodejs_ver }} install"
  include_tasks: install_nodejs_debian_family.yml
  when: (ansible_facts['os_family'] == "Debian") and ("nodejs" not in ansible_facts.packages)

- name: "[RedHat Family] [Neovim] Run NodeJS {{ nodejs_stream }} install"
  include_tasks: install_nodejs_redhat_family.yml
  when: (ansible_facts['os_family'] == "Redhat") and ("nodejs" not in ansible_facts.packages)

- name: "[Debian Family] [Neovim] Run Neovim install play"
  include_tasks: install_neovim_debian_family.yml
  when: ansible_facts['os_family'] == "Debian"

- name: "[RedHat Family] [Neovim] Run Neovim install play"
  include_tasks: install_neovim_redhat_family.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: "[All OS Types] [Neovim] Run configure play"
  include_tasks: configure_neovim.yml
  when: (not nvim_conf_dir.stat.exists)
