---
- name: "Set owner of SSH dir to {{ remote_host_user }}:{{ remote_host_user }}"
  hosts: all

  tasks:
    - include_role:
        name: ../../roles/security/ssh-setup
        tasks_from: fix_ssh_dir_owner
