---
- name: Configure Neovim
  hosts: all

  tasks:
    - ansible.builtin.import_role:
        name: common/install/install-neovim
        tasks_from: install_nodejs_debian_family.yml
      when: ansible_facts['os_family'] == "Debian"

    - ansible.builtin.import_role:
        name: common/install/install-neovim
        tasks_from: install_nodejs_redhat_family.yml
      when: ansible_facts['os_family'] == "RedHat"
