---
- name: Install Duplicati
  hosts: all

  vars:
    # defaults file for duplicati
    duplicati_web_port: 8200
    duplicati_ver: "2.0.6.3"

  roles:
    - { role: roles/common/install/install-duplicati }
