---
- name: "Install CNI plugins"
  hosts: all

  vars:
    ## TODO: Move cni_* vars to group_vars for inventory
    cni_app: cni
    cni_version: 1.3.0
    cni_os: linux
    ## amd64, arm, arm64
    cni_arch: arm64
    cni_dl_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-{{ cni_os }}-{{ cni_arch }}-v{{ cni_version }}.tgz"
    cni_plugins_dir: /opt/cni/bin
    cni_plugins_dir_mode: "0755"

  roles:
    - { role: roles/common/install/install-cni-plugins }
