---

## Debian
- name: Install required packages on Debian family OS
  become: true
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - "htop"
    - "git"
    - "dos2unix"
    - "wget"
    - "curl"
    - "neovim"
    - "tmux"
    - "unzip"
    - "zip"
    - "ncdu"
    - "arp-scan"
    - "python3-pip"
    - "python3.10-venv"
    - "python3-argcomplete"
  when: ansible_facts['os_family'] == "Debian"