---
# handlers file for setup/ssh
- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart SSH service
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
  become: true
